### ISSUE TITLE
Kustomer 2.0 SDK support

### ISSUE THREAD

**Issue by sstimac** [rebythecode/react-native-kustomer-sdk#3]
First of, thank you very much for this library !

Are there plans in the near future to support [2.0 versions](https://developer.kustomer.com/chat-sdk/docs) of the native SDKs ?

We are currently using your library to implement Kustomer in our apps, and would very much like to avoid forking the lib if the support for this is something coming in the near future. Thanks !

**Comment by aitorct** [comment]
Hey @sstimac! 👋 
Yes, we are planning to upgrade to the Kustomer Chat 2.0 SDK. Support for Chat 1.0 will end on September 30th.
We are currently busy with other projects so it might come later this year, but we'll definitely upgrade to Chat 2.0 on time. PRs are welcome too! 😄

**Comment by pauleta6** [comment]
This is done now in the latest version. Closing this issue!
